language: generic
sudo: false

git:
  depth: 1

notifications:
  webhooks:
    urls:
      - https://discord.com/api/webhooks/743427528735326258/96mlS4O9ElPigRp0LcD3-I2j4M37pdY_UG0oHugpgd-YpTLNPL7PSt3DHCxj420uYmOT
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

env:
    global:
    - BYOND_MAJOR="513"
    - BYOND_MINOR="1528"
    - DM_BUILDFILE="cev_eris.dme"

matrix:
  include:
    - name: "Run Linters - Dreamchecker"
      env:
        - SPACEMAN_DMM_VERSION=suite-1.5
      cache:
        directories:
          - $HOME/SpacemanDMM
      install:
        - tools/travis/install_spaceman_dmm.sh dreamchecker
      script:
        - ~/dreamchecker

    - name: "Compile"
      addons:
        apt:
          packages:
            - libc6-i386
            - libgcc1:i386
            - libstdc++6:i386
      cache:
        directories:
            - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
      install:
        - chmod +x ./install-byond.sh 
        - ./install-byond.sh
      script:
        - (! grep -rn 'step_[xy]' maps)
        - (! grep -Ern "(/obj/machinery/door/firedoor).*\1" maps)
        - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
#       - bash dm.sh -M${DM_MAPFILE} ${DM_BUILDFILE}
        - bash dm.sh ${DM_BUILDFILE}






